# Generated by Django 3.1.7 on 2021-03-04 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelname', models.CharField(max_length=255)),
                ('travelquestions', models.TextField(blank=True, null=True)),
                ('dateentered', models.DateField()),
                ('questions', models.TextField()),
            ],
            options={
                'db_table': 'traveltype',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelname', models.CharField(max_length=255)),
                ('dateentered', models.DateField()),
                ('travelprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reservedurl', models.URLField()),
                ('questions', models.TextField()),
                ('traveltype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cruise.traveltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontitle', models.CharField(max_length=255)),
                ('questiondate', models.DateField()),
                ('questiontext', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cruise.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
